
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:/software3_fivegroups?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

  transaction:
    rollback-on-commit-failure: true
    default-timeout: 30
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
